### ISSUE TITLE
JP: Different format if using latin

### ISSUE THREAD

**Issue by nahkampf** [rinvex/countries#100]
This popped up in production for us:

Some japanese users type their adresses using latin characters instead of katakana, and per the recommendations (https://www.post.japanpost.jp/int/use/writing/ems_en.html) such addressing should be reversed (ie the traditional "western" addressing system, ie name, followed by street, followed by zip and city etc).

It also gets quite confusing when westernized addresses are used since the JP format looks like this:
`〒{{postalcode}}\n{{region_short}}{{city}}{{street}}\n{{recipient}}\n{{country}}`
ie, no separator between region, city and street.

So maybe we need a jp-westernized.json file, with a format something along the lines of
`{{recipient}}\n{{street}}\n{{postalcode}}{{city}}\n{{region_short}}\n{{country}}`

As to how we would select that format instead of the official JP one I'm not sure. A helper function to analyze if the address contains mostly latin characters or not maybe? Or just a flag to pass (westernized=true)?

**Comment by Omranic** [comment]
Thank you @nahkampf for your suggestion, I'm not sure what's the best way to do that, and if that's something that affects other countries too. If you can help by submitting a PR contributing this change, I'll be happy to consider it. All PRs are welcome 😉
