### ISSUE TITLE
How to add country translation name?

### ISSUE THREAD

**Issue by mohamedsabil83** [rinvex/countries#116]
I want to add an Arabic translation name for all countries. Where is the right file to put it?

**Comment by Omranic** [comment]
Thank you for your patience.

Well, that's not something supported by this package as it depends on your application layer, more than the core package.

This package returns country names in the native languages spoken in the countries, and doesn't natively allows for custom translations. The reason behind that is that anyone can ask for any other translations, like Chinese translation for a country names for example, which may not be useful for large segment of package users, and will bloat the package with unnecessary data.

My suggestion is to handle that on your application layer, let's say in a helper function or a controller action, where you can retrieve all country codes, and put an array with their Arabic translated names, that way you'll be able to get the results you're looking for.
