### ISSUE TITLE
Wrong php function uses in getLanguages()

### ISSUE THREAD

**Issue by ludo237** [rinvex/countries#117]
I'm referencing [this line](https://github.com/rinvex/countries/blob/e3bef1d28578e04f8ae0fd328f1b648cfa17d6f6/src/Country.php#L281)

It should be `mb_strtolower` instead of `mb_strtoupper`

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in https://github.com/rinvex/countries/commit/e13ef296a02eedb85a2fe5f77b671449a11875ea
