### ISSUE TITLE
[Proposal] Document laravel related features

### ISSUE THREAD

**Issue by jhm-ciberman** [rinvex/countries#119]
I think this is a super great package, but it seems that all the amazing laravel features are undocumented. 
I've made a checklist for things to document

- [ ] Helpers (`country` and `countries`)
- [ ] `country` Validator rule
- [ ] Auto Laravel ServiceProvider discovery

**Comment by Omranic** [comment]
What about a PR ;)

**Comment by jhm-ciberman** [comment]
Sounds like a nice idea :)
I'm happy to help. I will try to find a time during this week. Thanks.

**Comment by Omranic** [comment]
Will close this for now due to inactivity, but feel free to re-open for discussion if needed. And PRs are still welcome as well 😉
