### ISSUE TITLE
Guinea-Bissau Flag & official name of Portugal 

### ISSUE THREAD

**Issue by lbassuncao** [rinvex/countries#143]
Hi.

For some reason Guinea-Bissau flag is not right. The ISO-2 code is gw.
see the difference: https://en.wikipedia.org/wiki/Guinea-Bissau.

The translation for Portuguese of the official name of Portugal is "República Portuguesa" and not "República português".

Thanks.

**Comment by Omranic** [comment]
Thank you @assunluis80 will you be able to submit a PR for this update?

**Comment by assunluis80** [comment]
@Omranic yes. Of course. Will do it soon. Thanks.

**Comment by lbassuncao** [comment]
I'm sorry to bother you @Omranic, this my first PR ever to an Open Source project. What this mean? It's been rejected? :)

**Comment by Omranic** [comment]
Thank you @lbassuncao for your efforts, much appreciated.

However I'd suggest to submit granular PRs for each update. Example: 1 PR for changing Portugal Name, and another PR for changing Guinea Flag. I tried to update your PR and merge it, but couldn't. (the flag isn't quite right, syntax wise)

I'll apply the Portugal name change, and will update the flag in a another change as well. Thanks, and please don't hesitate to submit future PRs, it's helpful 👍 

Fixed here:
https://github.com/rinvex/countries/commit/fcd25855c089bfc599b90b81efa4ea9eb3ab694f and will update the flags in another commit. Thanks again.

**Comment by Omranic** [comment]
Flags are now fixed in https://github.com/rinvex/countries/commit/27df29d7778570e3384bcadde72076fdde73b190
