### ISSUE TITLE
PHP 7.4 as minimum?

### ISSUE THREAD

**Issue by thijsw** [rinvex/countries#145]
Hi, I was wondering why PHP 7.4 is required as a minimum PHP version for this package.

This seems to me as a very simple package, does it need any features introduced in version 7.4?

A lot of servers are still running older versions of PHP; by requiring 7.4 a lot of projects are excluded to use this package unfortunately.

**Comment by Omranic** [comment]
Hello, thank you for your feedback.

Feel free to use v6.x which requires PHP v7.2 as minimum version, and it's pretty stable as well 🙂 

Stay healthy, stay safe.

**Comment by rognales** [comment]
Hopefully, non breaking changes do flow down to 6.x branches. Thx
