### ISSUE TITLE
Regions and cities

### ISSUE THREAD

**Issue by altynbek07** [rinvex/countries#165]
Hi. Is there a similar package for regions and cities?

**Comment by Omranic** [comment]
Thank you @altynbek07 for your question, I'm not aware of something complete that serves your purpose, but I'm willing to add that info to this package to make it complete reference for everything related to country data, including regions and cities. Check this potential discussion #23

I'll be happy to consider PRs adding that info to this package, that would help. All PRs are welcome 😉
