### ISSUE TITLE
Countries Affected by GDPR

### ISSUE THREAD

**Issue by simoheinonen** [rinvex/countries#170]
https://www.defensorum.com/gdpr-countries-list/

**Comment by choval** [comment]
There's a `isEuMember()`, which I've used to detect if a user is from an EU country and mark accordingly for GDPR.

**Comment by simoheinonen** [comment]
That's not accurate enough. GDPR is also used in UK, Iceland and Norway for example which aren't EU countries.

**Comment by ninjahza** [comment]
Jumping on this

**Comment by choval** [comment]
The thing with GDPR, is that some other countries have similar laws but not GDPR specifically... For example Argentina, Brazil, Canada, Japan and many others have similar personal data handling requirements. A 'data protection' flag would be more useful.

Or you could easily just create a list with the country codes in the list you provided to check for GDPR specifically.

**Comment by Omranic** [comment]
Thank you for your suggestions. This is a very interesting feature that I would love to have implemented in this package.

I'll be happy to consider PRs adding that feature in this package, all PRs are welcome 😉
