### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by rawilk** [rinvex/countries#175]
Please add support for php 8.

To get around this for now, I'm running `composer update --ignore-platform-reqs` so I can successfully run the command, but adding that flag is not ideal.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rinvex/countries is locked to version v6.1.2 and an update of this package was not requested.
    - rinvex/countries v6.1.2 requires php ^7.2.0 -> your php version (8.0.0RC3) does not satisfy that requirement.
```

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest major release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @rawilk @4-FLOSS-Free-Libre-Open-Source-Software

**Comment by rawilk** [comment]
Thank you! Much appreciated.

**Comment by craigrileyuk** [comment]
Thanks for keeping this up-to-date. Really appreciated.
