### ISSUE TITLE
Vietnam's flag seems broken

### ISSUE THREAD

**Issue by choval** [rinvex/countries#180]
SVG rendered in chrome: <img width="40" alt="Screen Shot 2021-02-18 at 22 00 02" src="https://user-images.githubusercontent.com/794926/108441808-b118f200-7234-11eb-82e4-f4188346c5eb.png">

It's missing the bottom two corners of the star.

Emoji: 🇻🇳

**Comment by Omranic** [comment]
Thank you for reporting this, flags are now fixed in https://github.com/rinvex/countries/commit/27df29d7778570e3384bcadde72076fdde73b190
