### ISSUE TITLE
Divisions ISO2 codes are not updated.

### ISSUE THREAD

**Issue by sathiyad** [rinvex/countries#186]
ISO2 codes for divisions are not updated with new ISO2 values. 
Example:
Country: China
State: Beijing Shi
[Divisions json](https://github.com/rinvex/countries/blob/master/resources/divisions/cn.json) is returning the division code as _11_ but it's updated to _BJ_ already (2017). Also, some division's names are not updated ex: India - Pondicherry updated to India - Puducherry.
[Ref to China divisions update](https://en.wikipedia.org/wiki/ISO_3166-2:CN)

**Comment by Omranic** [comment]
I'll be happy to consider PRs adding missing divisions, or updating existing ones. All PRs are welcome 😉
