### ISSUE TITLE
Italy detail in shortlist.json is incorrect.

### ISSUE THREAD

**Issue by shazahm1** [rinvex/countries#192]
As the subject states, the details for Italy are incorrect. It is the following:

`"it":{"name":"Italy","official_name":"Italian Republic","native_name":"Italien","native_official_name":"Italienische Republik","iso_3166_1_alpha2":"IT","iso_3166_1_alpha3":"ITA","calling_code":"39","currency":"EUR","emoji":"🇮🇹"}`

And it should be:

`"it":{"name":"Italy","official_name":"Italian Republic","native_name":"Italia","native_official_name":"Repubblica italiana","iso_3166_1_alpha2":"IT","iso_3166_1_alpha3":"ITA","calling_code":"39","currency":"EUR","emoji":"🇮🇹"}`

It looks like perhaps the german translation is being used instead???

**Comment by Omranic** [comment]
Thank you for raising this, it's now fixed in https://github.com/rinvex/countries/commit/46676637861917e5436e9c1ec2eb53dbfb1d2c39
