### ISSUE TITLE
Please update Belarus for German (deu)

### ISSUE THREAD

**Issue by ms-zlab** [rinvex/countries#211]
Can you please update the translation of Belarus for Germany (deu)? "Weißrussland" has not been used officially since 2021 and has therefore come under fire.

https://github.com/rinvex/countries/blob/947031400fecc1c9f2f639d86e2113ee6cb09c37/resources/translations/by.json#L1

https://de.wikipedia.org/wiki/Belarus#%E2%80%9EWei%C3%9Frussland%E2%80%9C_und_%E2%80%9EBelarus%E2%80%9C

https://www.auswaertiges-amt.de/blob/215256/329771379c1c045ecd02eed3e3667df0/laenderverzeichnis-data.pdf

**Comment by Omranic** [comment]
Can you please submit a PR to fix this, also if there's a newspaper or official announcement explaining that change as I couldn't understand exactly what happened from the provided links above..

**Comment by ms-zlab** [comment]
Hello @Omranic , can you please accept the change?
