### ISSUE TITLE
Italy native name and main language

### ISSUE THREAD

**Issue by costafrancesco94** [rinvex/countries#226]
Hello :)

I would like to point out an issue...

In `Italy` files, we have the 3 translation of the common and official name in the native languages.

Problem is, main language of Italy is wrong (it does return the first one, not the main one)
```
getLanguage() // "Austro-Bavarian German"
getLanguages() // Object { bar: "Austro-Bavarian German", ita: "Italian", srd: "Sardinian" }
```

Problem is there is no way to determine what is the **main** language of the country.

**Comment by Omranic** [comment]
@costafrancesco94 thank you for pointing this out, I believe this needs cleaning and a fix similar to what we did with the `currency` here https://github.com/rinvex/countries/commit/1cf372b29bc0c17eeaf08e40a7cd98b729aae296

All PRs are welcome 🙂 🙌
