### ISSUE TITLE
Oddity with Bonaire translations

### ISSUE THREAD

**Issue by acjbizar** [rinvex/countries#227]
For `bq`, I noticed the data JSON does not have the Dutch translation under `nld` like the other flags do, but under `dut` (which, to be fair, is a valid ISO 639-2 Language Code for Dutch; it’s just different from the others). What’s more odd is that the common name under that key is “Besondere Gemeinde (Niederlande).” That’s not even Dutch; its German. The common name for `bq` in Dutch should be “Bonaire.” Is that something that can be fixed in this repository, or is this data taken from an external repository that I should address?

**Comment by Omranic** [comment]
@acjbizar sure, this can be fixed in this repo. PRs are welcome 🙂 🙌 

Also if you want to check some of the data resources we used to build this package, you can check the following section https://github.com/rinvex/countries#data-sources
