### ISSUE TITLE
Get country codes by region

### ISSUE THREAD

**Issue by sts-ryan-holton** [rinvex/countries#234]
Hi,

I'm developing a Laravel application based on SMS messaging. My application allows users to send messages to different regions, for example, Europe, Worldwide, US/Canada, Americas etc...

Does this package support fetching all country codes by a region?

For example:

`EUR` would fetch me all of the country codes for this region, which I could then, when validating a phone number check the country code exists.

Again, I'm evaluating whether I can install and invest some time into this package.

**Comment by Omranic** [comment]
Hey @sts-ryan-holton, thanks for the good question.

Yep, you can do that using a couple of ways, for example:

```php
// Get countries with where condition (continent: Europe)
$euCountries = \Rinvex\Country\CountryLoader::where('geo.continent', ['EU' => 'Europe']);

// Or get countries with where condition (region: Europe)
$euCountries2 = \Rinvex\Country\CountryLoader::where('geo.region', 'Europe');
```

Check here a couple more usage examples https://github.com/rinvex/countries#usage
