### ISSUE TITLE
Feature: 'phone_format'

### ISSUE THREAD

**Issue by tfont** [rinvex/countries#37]
Just like 'address_format', just one for numbers.

Example:
+352 691 123 4567
// {{callingcode}} {{initial}} {{range1}} {{range2}}

I don't know the actual names, but basically that.

**Comment by Omranic** [comment]
Good feature request, will consider this in future updates

**Comment by Omranic** [comment]
I'll be happy to consider a PR to add this info to the package, all PRs are welcome 😉
