### ISSUE TITLE
Translations of divisons

### ISSUE THREAD

**Issue by marvinschroeder** [rinvex/countries#51]
Are there any plans in making the alternative names of the division as translations, where i can map the alternative name to a language? I think the default name of a divison is in the native language, but how do i know which alternative name is for what language?

**Comment by Tigrov** [comment]
You can find translations for divisions from Wikipedia at 
https://github.com/Tigrov/wikipedia-divisions/blob/master/result/names.csv

**Comment by Omranic** [comment]
This is a good enhancement, thank you for your suggestion. I'll be happy to consider PRs adding this feature, all PRs are welcome 😉
