### ISSUE TITLE
[Proposal] Add electricity type

### ISSUE THREAD

**Issue by jackbraj** [rinvex/countries#53]
Can you please consider adding electricity voltage types a country have?

**Comment by Omranic** [comment]
Sounds interesting, do you know a central place where we can collect these data? 🤔 
PRs always welcome 😉

**Comment by optiman** [comment]
U.S. International Trade Administration has some information about that:
http://www.trade.gov/mas/ian/ECW/all.html

Although some records seem obsolete. Many ex-USSR countries (like Ukraine) converted from 220V to 230V in the last decades.

**Comment by jackbraj** [comment]
I came across [this](http://www.worldstandards.eu/electricity/plug-voltage-by-country/) one. It seems most up to date but less comprehensive.

**Comment by Omranic** [comment]
Thank you for all the information, I'll be happy to consider a PR to add this info to the package, all PRs are welcome 😉
