### ISSUE TITLE
how to get country list by languages only ?

### ISSUE THREAD

**Issue by 8lbiasian** [rinvex/countries#54]
i try to do this 
`\Rinvex\Country\CountryLoader::where('languages', 'Arabic');`

but its not working 
even i try with passing an array ['value' => 'Arabic'] 
but also same issue 

can anyone help me with this 

thank you.

**Comment by pierrocknroll** [comment]
Did you find a solution ?

**Comment by Omranic** [comment]
The right way to do that search is as follows:
`\Rinvex\Country\CountryLoader::where('languages', ['eng' => 'English']);`

I know it's not intuitive, maybe we can simplify the API in the future. PRs are welcome 🙂
