### ISSUE TITLE
England fifa codes

### ISSUE THREAD

**Issue by ronnievisser** [rinvex/countries#59]
Hi,

Why does england has 4 fifa codes and not just ENG? according to wikipedia it should only be ENG.

**Comment by Omranic** [comment]
ENG: England
NIR: Northern Ireland
SCO: Scotland
WAL: Wales

https://en.wikipedia.org/wiki/List_of_FIFA_country_codes

**Comment by ronnievisser** [comment]
I know that but does england has them all 4.

**Comment by Omranic** [comment]
As I see these four FIFA codes are under *United Kingdom* not _England_, however if you believe this is not accurate, please feel free to submit a PR fixing this, I'll be happy to consider it. All PRs are welcome 😉
