### ISSUE TITLE
Caribbean Netherlands / Curaçao dailling code issues

### ISSUE THREAD

**Issue by Omranic** [rinvex/countries#79]
Reference: Fahed Bizzari

Thanks for developing the country library. We're about to replace lots of our code with it.

However, there are a couple of issues:

1. Caribbean Netherlands (BQ) should have a dialling code of +599 ([see here](https://en.wikipedia.org/wiki/Caribbean_Netherlands))
2. Curaçao (CW) should have a dialling code +599 not +5999.

Any way for you guys to get these updated?

**Comment by bevss** [comment]
Getting the same issue. Another one is "Saint Helena (SH)" should have a dialling code of +290 [(see here)](https://en.wikipedia.org/wiki/Saint_Helena)
