### ISSUE TITLE
ISO 639-1 Language codes

### ISSUE THREAD

**Issue by drdrak3** [rinvex/countries#85]
Any chance of implementing [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes instead of [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) codes?
PHP plays better with [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes: http://php.net/manual/en/locale.getdisplaylanguage.php

At the moment I'm resorting to a helper class just to convert [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
```
$languages = [
    ['ab', 'abk'],
    ['aa', 'aar'],
    ['af', 'afr'],
    ['ak', 'aka'],
    ['sq', 'sqi'],
    ...
];
```

**Comment by Omranic** [comment]
That's very good point, if you can help with PR that would be much appreciated ^_^

**Comment by Omranic** [comment]
I gave it a try, but this is more complicated than I thought, it requires breaking changes, and changing how the country languages and translations are handled.

Tak *Afghanistan* as an example, when you check it's native name, you'll find it available in three language dialects: `prs`, `pus`, and `tuk`. Both `prs` and `pus` belongs to the same `fa` language. Then what should we do in that case?

There's some options we can do here, but all as I see require doing breaking changes, and changing how we handle languages and translations.

Still, I'll be happy to consider PRs, all PRs are welcome 😉
