### ISSUE TITLE
Countries with multiple divisions levels

### ISSUE THREAD

**Issue by drdrak3** [rinvex/countries#86]
GB has multiple division levels, and currently the dataset has all divisions levels combined into one.
Eg. [Derby](https://en.wikipedia.org/wiki/Derby) and [Derbyshire](https://en.wikipedia.org/wiki/Derbyshire) exist in the one list.

This seems to be an issue that has stemmed from https://github.com/hexorx/countries
Would be nice if this could be fixed, other countries may be affected as well.

If my need becomes more pressing, I will make a pull request to fix GB divisions.
But this will need to be properly looked into for all countries.

**Comment by Omranic** [comment]
PR would be much appreciated ^_^
