### ISSUE TITLE
Demonym translations

### ISSUE THREAD

**Issue by seb-jean** [rinvex/countries#9]
Hello,

It would be nice to have the translations demonyms :).

**Comment by Omranic** [comment]
Yeah, I agree. Feature request considered for implementation.
Feel free to submit PR if you'd like to contribute some translations 😉

**Comment by ph-il** [comment]
Translation in French:        
switch ($country->getIsoNumeric()) {
            case 535:
                return 'Bonaire';
            case 654:
                return 'Sainte-Hélène, Ascension et Tristan';
        }
