### ISSUE TITLE
Flag is very large

### ISSUE THREAD

**Issue by mohamedsabil83** [rinvex/countries#90]
Can I change the size of the flag cause it's very large **750 widths** and **500 height**?

**Comment by Omranic** [comment]
Sure you can, it's SVG anyway so feel free to use it the way you want :)

**Comment by ludo237** [comment]
@mohamedsabil83 @Omranic how can I update the SVG size on demand?

**Comment by mohamedsabil83** [comment]
You can do it by setting the **Height** and **Width** attributes. You can paste your code for more help.

**Comment by ludo237** [comment]
@mohamedsabil83 I actually send the country class to a view using Blase template (from Laravel)

Something like this

```Blade
<div>{{ $country->getFlag() }}</div>
```

**Comment by mohamedsabil83** [comment]
It's a workarownd. You can do it like this:

**Blade**
```html
<div class="flag">{!! $country->getFlag() !!}</div>
```
**Css**
```css
.flag svg {
    width: 100px;
    height: 50px;
}
```

**Comment by ludo237** [comment]
Damn I should have thought about that. Thank you very much

**Comment by mohamedsabil83** [comment]
Your welcome

**Comment by ludo237** [comment]
It does not work 😢

**Comment by shazahm1** [comment]
CSS should be used to size the flags, the SVG flag files do not need sized because, well, since they are vectors, they have no size (technically).

**Comment by mohamedsabil83** [comment]
@ludo237 [codepen](https://codepen.io/) your code to review it .

**Comment by ludo237** [comment]
Never mind my fault, it works as intended! 

Sorry

**Comment by mohamedsabil83** [comment]
Good to know that.

**Comment by ludo237** [comment]
Sorry to brings this up again but I figured out what was wrong, basically it's not me but some flags I am using the style provided by @mohamedsabil83 for this

I mean take a look at the screen shots here, this flag is rendered correctly: 
![image](https://user-images.githubusercontent.com/921500/54604339-d0a2b100-4a46-11e9-923c-0b9751fe73f0.png)
Inspect element of this flag is
![image](https://user-images.githubusercontent.com/921500/54604457-0ba4e480-4a47-11e9-8a6b-cb9b7d85e5e6.png)


While this clearly is not rendered correctly 
![image](https://user-images.githubusercontent.com/921500/54604396-ed3ee900-4a46-11e9-877f-0594f2890584.png)
Inspect element of this flag is
![image](https://user-images.githubusercontent.com/921500/54604490-224b3b80-4a47-11e9-8264-20c0d1cf10a3.png)

Some flags have viewBox and title while other don't, the global style is this for what matters
![image](https://user-images.githubusercontent.com/921500/54604523-3db64680-4a47-11e9-854e-5766ee315c62.png)
I'm using bootstrap 4 hence the `@extend .mr-2`

**Comment by ludo237** [comment]
I ended up leveraging a npm package called `flag-icon-css` then I simply do

![image](https://user-images.githubusercontent.com/921500/54987635-34802900-4fb5-11e9-91cc-052f964e25b4.png)

And it works like a charm.

**Comment by mohamedsabil83** [comment]
Yes, It's another way. good to share it.
